services:
  api:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      DATABASE_NAME: todoApp
      HOST: mongodb
      PORT: 27017
      USERNAME: root
      PASSWORD: rootpassword
      DATABASE_URL: mongodb://root:rootpassword@mongodb:27017/
      AUTH_SOURCE: admin
      JWT_SECRET_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIuzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3NDI2MDE2MDUsImV4cCI6MTc3NDEzNzYwNSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.ypO0f9ZMfRHa_ZkQxNL1y51hcTwz2y_yjx5-l6RlkVI
      JWT_ACCESS_TOKEN_EXPIRES: 3600 # 1 hour
      JWT_REFRESH_TOKEN_EXPIRES: 604800 # 7 days
    depends_on:
      - mongodb
    restart: unless-stopped
    command: flask run --host=0.0.0.0 --reload
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
volumes:
  mongodb_data: